#+TITLE: Bauprozess Ökonomie
#+SUBTITLE: Mitschriften und Notizen
#+AUTHOR: Christian Sangvik
#+EMAIL: christian.sangvik@gmx.ch
#+DATE: <2018-02-19 Mon>

#+LATEX_HEADER: \usepackage{ngerman}

* Administratives

** Semesterplanung

   | 19. Feb   | 01 | Editorial              |
   | 26. Feb   | 02 | Die Ökonomie der Stadt |
   | 05. Mär   | 03 | Renditen               |
   | 12. Mär   | 04 | Chancen & Risiken      |
   | 19. Mär   | -- | Seminarwoche           |
   | *26. Mär* | 05 | *benotete Übung I*     |
   | 02. Apr   | -- | Osterferien            |
   | 09. Apr   | 06 | Kosten                 |
   | 16. Apr   | -- | Sechseläuten           |
   | 23. Apr   | 07 | Projektentwicklung     |
   | 30. Apr   | 08 | Die Genossenschaft     |
   | *07. Mai* | 09 | *benotete Übung II*    |
   | 14. Mai   | 10 | Wrap-Up                |

   - zwei benotete schriftliche Übungen während des Semesters
   - Vorlesung ist Grundvoraussetzung für Wahlfacharbeit
   - Kontrollierte Anwesenheitspflicht
   - [[http://www.bauprozess.arch.ethz.ch/education/MSc/BauprozessOekonomie.html][Vorlesungsfolien online verfügbar]] (werden jeden Montag aufgeschalten)

** Wahlfacharbeit

   In diesem Vertiefungsfach ist eine Wahlfacharbeit möglich. Diese wird
   prinzipiell als Einzelarbeit geführt, und es ist mit einem Aufwand von
   ca. 150 Semesterstunden gerechnet. Die Abgabe der Arbeit erfolgt in
   schriftlicher Form.

   Genauere Informationen folgen.

** Literaturempfehlungen

   - Drei Bücher über den Bauprozess (S. Menz)
   - Immobilienökonomie und Bewertung von Liegenschaften (Kaspar Fierz)
   - Die Immobilienbewertung (Francesco Canonica)
   - The Ascent of Money (Niall Ferguson)
   - Capital in the Twenty-First Century (Thomas Pikkety)

** Immobilien Oekonomie App

   [[https://ioe-app.ethz.ch][IOE App]] mit ETH Login verfügbar.

* Vorlesungen

** Editorial

*** Notizen

    5% Regel. Whg muss mit 5% Zinsen noch finanzierbar sein.

    Das Bauen hinkt immer ca. zwei Jahre hinter der Konjunktur her, da das Bauen
    an sich langsam ist. Somit kann man nicht direkt auf den Markt reagieren.

    Der Grossteil der Bauaufgaben wird auf Rendite und aus ökonomischen Motiven
    erteilt.

**** Wie entstehen Werte?

     Wie bestimmt sich der Grundstückspreis? Was bedeutet dies für uns
     Architekten?

*** Die Bauökonomie

    Die Bauökonomie ist in der Architektur bei jedem Projekt von Anfang an im
    Fokus. Vo der Aquise bis hin zur Bewirtschaftung ist sie wichtig. Daher ist
    es wichtig, sich von Anfang an Gedanken dazu zu machen.

    In der SIA Norm 102 kann man aber für die Ökonomie nur den Punkt "Schätzen
    des Finanzbedarfes" abrechnen.

    In der Praxis brauchen wir aber eine grosse ökonomische Kompetenz.

    Variabel ist leider in der Ökonomie nur die Baukosten. Deshalb verkommt der
    Architekt häufig zum geometrischen Dienstleister.

*** BKP

    BKP simuliert den Bauprozess.

    Der schwierigste Punkt der Schätzung ist das Land.

    Neben der Kostenseite gibt es aber auch die Ertragsseite.

** Die Ökonomie der Stadt, [[file:Vorlesungsfolien/02_Die_Oekonomie_der_Stadt_V.pdf][Folien]]

*** Einstieg

    Stadt - Abgeleitetes Wort von Stad, Standort, Stelle.

    In der Bewerbung von sehr teuren Bauten beispielsweise in New York, wird dem
    Gebäude keine Rechnung mehr getragen. Es wird nur noch mit der Lage
    geworben. Baurechtlich sind die gezeigten Bilder aber sehr fraglich, da seit
    1916 die ``Wedding Cakes'' in den /zoning laws/ vorgeschrieben sind.

    In New York kann man aber /air rights/ von Nachbarn dazukaufen.

    Ähnliches ist in Zürich mit den /Ausnützungstransfers/ möglich. So kann man
    höher und mit mehr Volumen bauen, als eigentlich vorgesehen.

    Die ökonomischen und rechtlichen Prinzipien von New York und Zürich sind
    durchaus vergleichbar, obwohl natürlich die Gebäude um einiges niedriger und
    kleiner sind.

    Ein Ertragssprung findet um das 5. - 7. Geschoss statt, da die
    Umgebungsbebauung niedriger ist, und man so einen viel weiteren Ausblick
    hat.

    Pro Geschoss wird der Wohnraum durchschnittlich um 3.17% teurer. Dadurch
    resultieren circa 25% mehr Einnahmen.

*** Die Stadt als ökonomisches Phänomen

    Warum die Menschen bereit dazu sind so viel zu bezahlen, um in der Höhe zu
    wohnen liegt in der Ökonomischen gegebenheit.

    In der Urproduktion waren die Menschen an die Fläche gebunden, um ihr
    Überleben zu sichern und genug zu produzieren. Durch technische Entwicklung
    und Spezialisierung mit Handel war nicht mehr jeder genötigt den Platz zu
    beanspruchen.

    Die die Spezialisierung machte auch Schutzmassnahmen notwendig. Schutz
    bedeutet Mauer, Turm und Befestigung. Somit waren die Spezialisten, die
    Technische und andere Güter herstellten die Begründer der ersten Städte.

    Je nach Art der Dienstleistung muss man näher des Zentrums sein. Die
    Bereitschaft zu zahlen nimmt aber generell ab, je weiter weg man vom Zentrum
    kommt.

    Beweggründe hierfür sind diverse Faktoren:

    - Time is money. Je höher der Stundenlohn, desto wichtiger ist die Zentralität.

*** Fokus Zürich

    Der Status einer Stadt ist nicht an ihre Grösse gebunden, sondern an ihre
    Wichtigkeit in diversen Bereichen. Zürich ist also unproportional wichtig zu
    ihrer Grösse.

    Zürich scheint relativ effizient auch in den Pendelströmen und Bewegungen.

**** Auktion: Objekt 1, Gironde

     1'096'000.- CHF

**** Auktion: Objekt 2, Seebach

     1'050'000.- CHF

**** Erklärungsansätze

     Die Kaufkraft in Frankreich ist nicht dieselbe wie in der Schweiz. Man
     müsste ungefähr 50% des Brutto-Median-Einkommens für das Schloss
     aufwenden. Das Medianeinkommen in der Gironde ist nur ca. 25'000
     CHF/Jahr. In Zürich ist es um 125'000 CHF/Jahr.

     Man sollte maximal 30% des Bruttolohns für Wohnkosten aufwenden.

     Das Einkommen und die Kaufkraft machen einen enormen Hebel aus auf die
     Kosten der Ligenschaften.

     Im Durchschnitt zahlt ein Zürcher aber nur ca 17% seines
     Bruttojahreseinkommens für das Wohnen.

     Die Preissteigerung von 3.7% pro Etage ist aber nur auf die Landkosten
     zurückzuführen. Die Erstellungskosten weichen bei weitem nicht so stark
     ab.

     Das *Verhältnis* der Anlagekosten zwischen der Erstellungskosten und dem
     Landwert heisst Lageklasse. Dieses Verhältnis ist in ähnlichen Lagen immer
     dasselbe, obwohl die absoluten Werte stark voneinander abweichen kann.

** Renditen

*** Einstieg

    Jede fünfte Hypothek wird aufgenommen um dsa Objekt später zu vermieten.

    Preise für Eigentumswohnungen sind so hoch, dass man sie eigentlich nicht
    gewinnbringend vermieten kann. Die Wertsteigerung des Landes muss höher
    sein, als die Abschreibung des Objektes. Der Landwert und die
    Immobilienkosten war von der Wirtschaftskriese unberührt. Land und
    Immobilien gelten als /cash-cows/.

*** Bieterverfahren

    Je nach Exklusivität wird ein Objekt an einen geschlossenen Kreis von
    Investoren ausgeschrieben, sonst generell öffentlich. Architekten gehen
    häufig für Investoren an Besichtigungen.

    In der zweiten Phase werden die paar höchstbietenden wieder Eingeladen und
    eine Finanzierung geprüft.

    Vertrauenshaftung [googlen] ist der Architekt haftbar. Man sollte sich
    dagegen versichern. Vor allem die rechtliche Situation ist in einem
    Vorprojekt und einer Machbarkeitsstudie abzuklären. Sie muss lückenlos
    stimmen.

    Sanierungsstau prüfen. Sanierungsstau bedeutet, dass der Vorbesitzer nichts
    mehr saniert hat mit der Absicht das Objekt sowieso zu verkaufen. Für
    umbauten das Baurecht prüfen (Nasszellen, Heizung, Lift, etc.)

    Altlasten prüfen.

    Bäume sind häufig geschützt. Fällgenehmigung häufig erforderlich.

    Risiko auch im Referenzzinssatz. Die Miete muss korrigiert werden. Es kann
    sein, dass die Bewohner zu hohe Zinsen zahlen, welche sie korrigieren
    müssen.

    Erträge eines Jahres = Nettomieten

    Glatte Renditezahlen, wie hier mit 5% kommen daher, dass der Verkäufer oder
    dessen Bank eine gute Rendite vorgiebt, um Investoren anzulocken. Sie ist
    häufig nicht die Reale rendite. Der Richtverkaufspreis wird dann anhand der
    Rendite gerechnet.

    Durch technische, gesellschaftliche und politische Entwicklung wurde die
    Rendite über die zeit immer tiefer. Das risiko war früher sehr viel höher
    als in unserer Zeit. Die Bruttorendite enthält eigentlich nur die
    Leerstandsrendite.

    Gesamtrendite (Performance) ist die Summe der Bruttorendite (Total der
    Einkünfte über die Anlagekosten) plus die Wertänderungsrendite
    (v.A. Wertsteigerung des Landes).

    Netto-Cashflow-Rendite

*** Brutto-, Netto-, Eigenkapitalrendite

** chancen & Risiken

** Kosten

** Projektentwicklung

** Die Genossenschaft

** Wrap-Up

* Aufbereitung
