#+TITLE: Bauprozess Ökonomie
#+SUBTITLE: Mitschriften und Notizen
#+AUTHOR: Christian Sangvik
#+EMAIL: christian.sangvik@gmx.ch
#+DATE: <2018-02-19 Mon>

* Administratives

  | 19. Feb | 01 | Editorial              |
  | 26. Feb | 02 | Die Ökonomie der Stadt |
  | 05. Mär | 03 | Renditen               |
  | 12. Mär | 04 | Chancen und Risiken    |
  | 19. Mär |  - | Seminarwoche           |
  | 26. Mär | 05 | benotete Übung         |
  | 02. Apr | 06 | Kosten                 |
  | 09. Apr |  - | Sechseläuten           |
  | 16. Apr | 07 | Projektentwicklung     |
  | 23. Apr | 08 | Die Genossenschaft     |
  | 30. Apr | 09 | benotete Übung II      |
  | 07. Mai | 10 | Wrap-Up                |

  - zwei benotete schriftliche Übungen, während des Semesters.
  - Anwesenheitspflicht. Wird kontrolliert.
  - Grundvoraussetzung für Wahlfacharbeit
  - [[http://www.bauprozess.arch.ethz.ch/education/MSc/BauprozessOekonomie.html][Vorlesungsfolien online]]. Werden jeden Montag augeschalten.

** Wahlfacharbeit

   Einzelarbeit, schriftlich. Ca. 150 Semesterstunden.

** Literaturempfehlungen

   - Drei Bücher über den Bauprozess (S. Menz)
   - Immobilienökonomie und Bewertung von Liegenschaften (Kaspar Fierz)
   - Die Immobilienbewertung (Francesco Canonica)
   - The Ascent of Money (Niall Ferguson)
   - Capital in the Twenty-First Century (Thomas Pikkety)

** Immobilien Oekonomie App

   [[https://ioe-app.ethz.ch][IOE App]] mit ETH Login verfügbar.

* Vorlesungen

** Editorial

*** Notizen

    5% Regel. Whg muss mit 5% Zinsen noch finanzierbar sein.

    Das Bauen hinkt immer ca. zwei Jahre hinter der Konjunktur her, da das Bauen
    an sich langsam ist. Somit kann man nicht direkt auf den Markt reagieren.

    Der Grossteil der Bauaufgaben wird auf Rendite und aus ökonomischen Motiven
    erteilt.

**** Wie entstehen Werte?

     Wie bestimmt sich der Grundstückspreis? Was bedeutet dies für uns
     Architekten?

*** Die Bauökonomie

    Die Bauökonomie ist in der Architektur bei jedem Projekt von Anfang an im
    Fokus. Vo der Aquise bis hin zur Bewirtschaftung ist sie wichtig. Daher ist
    es wichtig, sich von Anfang an Gedanken dazu zu machen.

    In der SIA Norm 102 kann man aber für die Ökonomie nur den Punkt "Schätzen
    des Finanzbedarfes" abrechnen.

    In der Praxis brauchen wir aber eine grosse ökonomische Kompetenz.

    Variabel ist leider in der Ökonomie nur die Baukosten. Deshalb verkommt der
    Architekt häufig zum geometrischen Dienstleister.

*** BKP

    BKP simuliert den Bauprozess.

    Der schwierigste Punkt der Schätzung ist das Land.

    Neben der Kostenseite gibt es aber auch die Ertragsseite.

* Aufarbeitung
