#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper,ngerman,11pt]

#+LATEX_HEADER: \usepackage{ngerman}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage{breakurl}
#+LATEX_HEADER: \addtokomafont{disposition}{\rmfamily}

#+OPTIONS: toc:nil

#+TITLE: Das Private im Öffentlichen Raum\\-- Paul Veyne --
#+LATEX_HEADER: \subtitle{Kommentar}
#+AUTHOR: Christian Sangvik
#+DATE: 4. März 2018

* Autor

  Paul Veyne ist ein französischer (Alt-)Historiker, spezialisiert auf die
  römische Geschichte. Er wurde am 13. Juni 1930 in Aix-en-Provence geboren,
  studierte an der /École normale supérieure/ und doziert seit 1976 als
  Professor für römische Geschichte am /Collège de France/ in Paris. Persönlich
  stand er Michel Foucault vor dessen Tod sehr nahe.cite:wiki:PaulVeyne-de

* Text

  Ein römischer Bürger hat ein Erbe, Familie, Klienten und /Ehren/. Die Ehren
  sind seine öffentlichen Ämter, die auf den Namen getragen werden wie ein
  Adelstitel.  Im antiken Rom unterschied man kaum zwischen öffentlich und
  privat, da die Öffentlichkeit das /private Kollektiv/ der /herrschenden
  Klasse/ war.cite:Veyne1989

  Die Öffentlichkeit der herrschenden Elite bestimmte alleine, wer zu ihnen
  gehörte, so ist sie im Gegensatz zu unserer Gesellschaft nicht allgemein,
  sondern selektiv. Die antike römische Öffentlichkeit ist also ein
  geschlossener Club der seine Mitglieder selber erwählt und dann innerhalb
  dieses mit seinem privaten Namen glänzt. Schwere /Missbräuche der Macht/ waren
  die Folge dieser Organisation. Die Missbräuche gingen so weit, dass sie in
  letzter Konsequenz sogar festgeschrieben wurden.cite:Veyne1989 Im Text löst
  Veyne die /öffentliche Aufgabe/ los vom Staat und portraitiert die römischen
  Staatsmänner eher als /Mafiapatron/. Machtmissbräuche die so weit gehen, dass
  sie später rechtlich niedergeschrieben und so im nachhinein legalisiert
  werden, kennen wir auch in die heutige Zeit hinein.

  Beispielsweise haben viele Staaten, darunter auch die Schweiz, gemäss den
  Aussagen Edward Snowdens aus dem Jahre 2013, ihre eigene Bevölkerung
  kathegorisch überwacht.cite:snowden In der Schweiz wurde zum nachträglichen
  Legalisieren das Überwachungs- und Nachrichtendienstgesetz (NDG) im Jahre 2016
  stillschweigend angepasst und nach erfolgreichem Referendum mittels
  Angstherrschaft aus der Landesregierung /(Die Bedrohungslage hat sich [...]
  verschärft.)/ cite:bundesrat bei der darauf folgenden Volksabstimmung im
  September 2016 forciert.

  Missbräuche der Macht waren ein essentieller Anteil in der Diskussion unseres
  Seminars in der Sitzung zu Hellers /Post-Privacy/ und gehören hier auch
  unbedingt hin, da sie Teil der Gegenwart sind.

  Im antiken Rom wurde den öffentlichen Ämtern aber ein immenser Stellenwert
  zugeschrieben. So soll G. I. Caesar seine /Würden/ selbst seinem Leben
  vorgezogen haben. In die politik zu gehen und damit öffentliche Aufgaben zu
  übernehmen hiess die Vollendung eines Menschen, eines idealen Privatmannes. Es
  wurde nicht einmal zwischen öffentlichen und privaten Mitteln
  unterschieden. Die meisten schönen Gebäude wurden aus privater Tasche
  bezahlt. Man nannte diese Praktik /Euergetismus/ (/politische
  Wohltaten/). Viele späteren Würdeträger kandidierten daher nicht selber für
  ein öffentliches Amt, sondern wurden dazu genötigt, und ihre Tradition und
  Herkunft forderte es von ihnen. Als Gegenleistung blieb der ewige Ruhm. Eine
  Lokalgrösse war keine Privatperson mehr; die Öffentlichkeit verschlang
  sie. Dieser Euergetismus war einzigartig in seiner Art, und hat bis heute keine
  Wiederkehr erlebt.cite:Veyne1989

  Aus der Sicht dieses Textes scheint es durchaus bemerkenswert, dass wir heute
  so sehr auf die Trennung zwischen öffentlich und privat pochen, da man sich
  nur in der Öffentlichkeit wirklich inszenieren kann. Wir sind aber
  aufgewachsen in einer Gesellschaft wo es weniger um Selbstinszenierung im
  grossen Massstab geht, als darum mitunter auch die Freiheit und Ruhe zu
  geniessen, die uns die private Abgeschiedenheit verspricht. Ich persönlich
  schätze diese Qualität mehr, als ein möglichst imposantes Bild meiner selbst
  in der Öffentlichkeit.Heutigen Politikern aber scheint es aber gemäss
  römischem Vorbild viel mehr um ihre Maske und Repräsentation als um
  /Kompetenz/ für ihre Ämter zu gehen.

bibliographystyle:unsrt
bibliography:dasprivateinderdigitalengesellschaft.bib
