#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper,ngerman,11pt]

#+LANGUAGE: de
#+LATEX_HEADER: \usepackage{ngerman}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage{breakurl}
#+LATEX_HEADER: \addtokomafont{disposition}{\rmfamily}

#+OPTIONS: toc:nil

#+TITLE: Grundfragen des Datenschutzes
#+LATEX_HEADER: \subtitle{Kommentar}
#+AUTHOR: Christian Sangvik

* Autor

  Wilhelm Steinmüller (* 29.5.1934, † 1.2.2013) war ein deutscher Jurist und
  Psychotherapeut. Er studierte Rechtswissenschaften, evangelische Theologie,
  Informatik und Volkswirtschaft. Später war er tätig als Professor für
  Kirchenrecht an der Uni Regensburg und ab 1982 Professor für angewandte
  Informatik an der Uni Bremen. 1990 legte er noch eine Ausbildung als
  Psychotherapeut ab.cite:wiki:Steinmueller-de Wie es seine Bildung vermuten
  lässt, hat er querbeet durch alle Fachrichtungen publiziert. Bemerkenswert
  hierbei auch für unser Seminar ist sein Lehrbuch für angewandte Informatik
  /Informationstechnologie und Gesellschaft/, das 1993
  erschien.cite:wiki:Steinmueller-de

  Alfred Bussey (* 10.11.1915, † 6.11.1987) war ein schweizer Nationalrat der
  SP.cite:wiki:Bussey-de Abgesehen von seiner politischen Laufbahn habe ich
  keine weiteren Angaben über ihn in Erfahrung bringen können.

* Text

  In Busseys Postulat können wir eine beginnende Skepsis gegenüber den
  Datenverarbeitungsmöglichkeiten durch Computer lesen. Die Gefahr kommt seines
  Erachtens aus dem Zusammenführen von Verschiedenen Informationen, die nicht
  zwingend miteinander zu tun haben, an zentrale Stellen, wo sie auch von
  anderenorts abrufbar werden. Also grundsätzlich sind die Probleme hinsichtlich
  des Persönlichkeitsschutzes der EDV die Geschwindigkeit und die Vernetzung.
  Zwar beschreibt er in einer positiven Stimmung und mit wörtlicher Ausführung
  des Vertrauens gegenüber den Staatsorganen (``[...] dass unsere Verwalgungen
  die so gesammelten Auskünfte mit der erforderlichen Zurückhaltung behandeln
  werden[...]'' cite:Computer1972) doch sind offensichtliche Bedenken über die
  selben Möglichkeiten von privaten (und somit unkontrollierbaren) Instanzen zu
  lesen (``[...] doch gilt dies nicht ohne weiteres für die privaten
  Unternehmen.'' cite:Computer1972). Er stellt den Antrag eine mögliche neue
  Gesetzgebung zu prüfen, die ``den Bürger und seine Privatsphäre gegen die
  missbräuchliche Verwendung der Computer schützen'' cite:Computer1972 aber auch
  ``eine normale Entwicklung der Verwendung von Computern ermöglichen''
  cite:Computer1972.

  Eine solche Gesetzgebung, die den Persönlichkeitsschutz abdeckt scheint aber
  sonderlich schwierig, wie wir dem /Gutachten/ von /Prof. Dr. W. Steinmüller et
  al./ entnehmen können. Das grundlegende Problem beim Schaffen eines solchen
  Gesetzes ist die unpräzise Natur des Begriffes der Privatsphäre. Dieses
  Problem ist, da es zum Kerninhalt unseres Seminares gehört, teil jeder
  Diskussion und wir tun uns bereits im kleinen Rahmen mit sehr wenigen Personen
  erstaunlich schwer, einen gemeinsamen Nenner zu finden, worum es sich
  eigentlich beim Begriff /Privatsphäre/ handelt. Dass sich dieses Problem, wenn
  es eine gesamte Bevölkerung betreffen soll, noch ungemein steigert scheint
  logisch.

  Im wesentlichen Beschreibt Steinmüller in seinem Gutachten, dass die
  Privatsphäre mit den aktuellen Gesetzen (von 1971 aber ich denke dass dies
  auch für die heutige Zeit gilt) nicht zu schützen ist.cite:Datenschutz1971 Es
  müssten also tatsächlich neue Gesetzesschriften geschaffen werden für diesen
  Zweck. Aber das Problem ist in der Unfassbarkeit des Begriffes
  /Privatsphäre/. Ein Versuch die Privatsphäre positiv zu definieren sieht er
  als gescheitert und gar unmöglich an (``Eine positive Inhaltsbestimmung ist
  wegen der Relativität der ``Privatsphäre'' unmöglich.''
  cite:Datenschutz1971). Diese Relativität hängt zum einen damit zu sammen, dass
  sich die Ansicht über den Inhalt der Privatsphäre über die Zeit ändern, und
  auch von Person zu Person, und darüber hinaus auch von wem Informationen
  offenbar werden sollen, abhängig ist.cite:Datenschutz1971 Ich denke dies genau
  spiegelt die Natur der Problematik besonders gut, wie wir auch in unserem
  Seminar jeweils zu differenzieren versuchen, welche unserer persönlichen
  Informationen nun privat sind, und welche nicht, und uns nicht einig werden
  darüber.

  Als erschreckend einleuchtenden Punkt, der sich von der Absicht einer jeden
  Rechtssprechung abheben muss führt Steinmüller auch das Argument ein, dass
  ``ihre [Privatsphäre] Schutzwürdigkeit in der Regel erst beurteilt werden
  kann, wenn sie bereits verletzt ist'' cite:Datenschutz1971, und dass demnach
  diese Beurteilung einiger Willkür seitens der Judikativen unterworfen ist.

  Nach dem Aufzeigen von Problemen bei einer neuen Rechtsimplementierung durch
  die Legislative oder durch die Judikative, welche jeweils andere Probleme mit
  sich bringen, aber keine geeigneter scheint, als die andere, führt Steinmüller
  auch andere Begriffe wie /Privatheit/, /Erheblichkeit/ cite:Datenschutz1971
  und /Identifizierbarkeit/ als mögliche Substitute des Begriffes /Privatsphäre/
  ins Feld, welche aber sicherlich niemals hinreichend eine Definition die
  rechtlich tauglich wäre zulassen. Er kommt zum Schluss, dass ``das Reizwort
  ``Privatsphäre'' [...] darum [Relativität, Unbestimmtheit und rechtliche
  unbrauchbarkeit] aus der wissenschaftlichen Diskussion des Datenschutzrechts
  auszuscheiden'' cite:Datenschutz1971 sei. Ein neuer Ansatz sei ``in der
  Anknüpfung an die Information und ihre Verarbeitung'' cite:Datenschutz1971.

  Ich für meinen Teil fand diesen Text sehr erleuchtend, und ich bin mir sicher
  nun ein wenig besser zu verstehen, warum Datenschutz aus rechtlicher Sicht
  nicht einfach sein kann. Auch bringt es mich zum Überlegen, meine generellen
  Forderungen für mehr Datenschutzgesetze auch für mich selber besser
  ausformulieren zu sollen.

bibliographystyle:unsrt
bibliography:dasprivateinderdigitalengesellschaft.bib
