#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper,ngerman,11pt]

#+LANGUAGE: de
#+LATEX_HEADER: \usepackage{ngerman}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage{breakurl}
#+LATEX_HEADER: \addtokomafont{disposition}{\rmfamily}

#+OPTIONS: toc:nil

#+TITLE: Soziologie
#+LATEX_HEADER: \subtitle{Kommentar}
#+AUTHOR: Christian Sangvik
#+DATE: 25. März 2018

* Autor

  Georg Simmel war ein deutscher Philosoph und Soziologe und begründete die
  /formale Soziologie/ und /Konfliktsoziologie/. Er wurde zu einer
  preisgekrönten Schrift über Kants Materiebegriff promoviert, nachdem seine
  eigentlich erste Dissertation über Musikethnologie abgelent wurde. Auch seine
  Hablilitationsschrift handelte über Kant, diesmal von dessen Lehre von Raum
  und Zeit. Allgemein stand Simmel in der Tradition des Neukantismus und der
  Lebensphilosophie.

  Sein Haus in Berlin wurde zu einem Ort des geistigen Austausches, wo sich
  Leute wie Rainer Maria Rilke Max Weber und viele mehr trafen. Da seine Familie
  eine jüdische Vergangenheit hatte, war es für Simmel im Deutschland um die
  Jahrhundertwende nicht einfach eine gebürende Anerkennung für seine Arbeit zu
  erhalten. Heute aber wird er von vielen als Begründer der deutschen Soziologie
  angesehen.cite:wiki:Simmel-de

* Text

  Simmel beschreibt im Textauszug Beweggründe für das Bilden von
  Geheimgesellschaften sowie die soziologisch-gesellschaftliche Wirkungsweise
  einer solchen. Die treibende Kraft für den Erhalt einer solchen geheimen
  Gesellschaft ist das Vertrauen der einzelnen Menschen die Teil einer solchen
  Gemeinschaft sind untereinander. Dafür bietet das geheime Kollektiv durch
  seine verborgene Natur Schutz für die einzelnen Menschen. Während die existenz
  eines Einzelnen nicht wirklich geheim sein kann, können doch Zusammenkünfte
  und Gemeinschaften eine vollkommen verborgene Existenz haben.cite:Simmel1992

  Eine Schwachstelle bildet hier der Umstand, dass wenn auch nur marginales oder
  gar Gerüchte über eine solche geheime Gesellschaft ans Licht kommen, diese
  weitere Angriffsmöglichkeit für das Enttarnen jener bietet. Somit schwebt bei
  einem Geheimbund immer auch die subtile Gefahr des Entdecktwerdens mit. Simmel
  schreibt wörtlich ``daß man mit Recht sagt, ein Geheimnis, um das Zwei wissen,
  sei keines mehr''.cite:Simmel1992 Dies ist auf zweierlei Arten
  problematisch. /Erstens/ muss das Geheimnis von mindestens zwei Leuten gewusst
  werden, wenn sie sich zusammentun unter dem Inhalt des Geheimnisses. Aber dies
  macht /zweitens/ die Sicherheit des Einzelnen vom Anderen abhängig. Man legt
  quasi seine eigene Sicherheit in die Hände des Anderen. Und wenn eine
  Gesellschaft geheim sein muss, dann ist dies wohl aus dem Grund, dass
  Praktiken oder Wissen, welches die Gesellschaft gemein haben wohl eher
  prekärer Natur sind, und so die Sicherheit, wenn der Bund auffliegt garantiert
  nicht gewärleistet werden kann.

  Die zugehörigen müssen sich zwangsläufig gegenseitig schützen um nicht
  entdeckt zu werden, was aber schwierig ist, selbst wenn keine Sabotage
  vorliegt, kein Maulwurf eingeschleust ist und dergleichen, da schon eine
  kleine Unachtsamkeit in einem willkürlichen Moment ausreichend sein kann um
  das Geheimnis auffliegen zu lassen. Im Laufe der Zeit haben verschiedenste
  Gesellschaften ganz unterschiedliche Wege gefunden um die einzelnen Mitglieder
  zu sensibilisieren, oder die Verschwiegenheit zu indoktrinieren.cite:Simmel1992

  Drei Bemerkungen oder Fragen, die mir beim Lesen des Textes aufgekommen sind
  möchte ich hier hervorheben:

  - Simmel beschreibt, dass die Schriftlichkeit an sich in ihrem Wesen der
    Geheimhaltung widerstrebt.cite:Simmel1992 Dies finde ich sehr einleuchtend,
    doch wissen wir auch, dass über die Geschichte viele Methoden gefunden
    wurden mit diesem Problem umzugehen. Der Text wurde entweder versteckt, so
    dass er für nicht Eingeweihte nicht auffind- oder lesbar war, oder aber er
    wurde verschlüsselt, so dass er für nicht Engeweihte selbst wenn er gefunden
    wurde keinen Sinn ergab. Dies sind auch die Schutzmechanismen, die wir im
    digitalen haben.
  - Durch die Schriftlosigkeit ist die Abhängigkeit von einzelnen Personen sehr
    gross. Dies gibt einem gewissen Individuum in der Gesellschaft einen hohen
    Stellenwert und Anerkennung. Die Gesellschaft ist abhängig von gewissen
    Schlüsselmitgliedern. Auf der anderen Seite sind diese aber auch im gleichen
    Masse abhängig von der Gesellschaft selber. Sie können mit ihrem
    Sonderwissen keinen Druck aufsetzen und sich übervorteilen, da ausserhalb
    der Gesellschaft dieses Können oder Wissen nichts wert ist. So kann sich
    kein allzu grosser Hebel der Ungerechtigkeit bilden. Alle sind letzten Endes
    von allen anderen abhängig.
  - Zuletzt habe ich mich gefragt, was wohl der Wert von Information ist. Wert
    meine ich hier in den Bedeutungen Gegenwert wie auch Sinn. Wenn ein
    Geheimnis brisant ist, kommen wir sicherlich schnell überein, dass dies eine
    wertvolle Information ist, die Schutz braucht. Wie sieht dies aber aus bei
    einer Banalität? Was ist der Wert einer Banalität? Man kann zwar
    argumentieren, dass sich niemand wirklich dafür interessieren mag, aber das
    bestehen eines Geheimnisses ist wie wir gelernt haben auch abhängig von ganz
    kleinen aussagen, die verraten könnten. Inwiefern gilt dies auch für die
    digitale Gesellschaft?

bibliographystyle:unsrt
bibliography:dasprivateinderdigitalengesellschaft.bib
